export function renderDesignTest() {
  const variants = ['Гостре', 'Капсула', 'Підкреслення', 'Ліва смуга', 'Верхня смуга', 'Inset', 'Плаваюча тінь', 'Подвійна рамка', 'Пунктир', 'Крапки', 'Без рамки', 'Темне', 'Градієнт', 'Кутове', 'Моноширинне', 'Велике', 'Компактне', 'Квадратне', 'Скляне', 'Паперова картка', 'Зелений акцент', 'Помаранчевий акцент', 'Фіолетовий акцент', 'Контурне', 'Внутрішня лінія', 'Тінь знизу', 'Тінь справа', 'Плоске', 'Підняте', 'Високий контраст'];
  const fields = variants.map((name, index) => `<label>${index + 1}. ${name}<input class="design-input design-v${index + 1}" placeholder="Приклад значення"></label>`).join('');
  const dates = variants.map((name, index) => `<label>${index + 1}. ${name}<input class="design-input design-v${index + 1}" type="date"></label>`).join('');
  const calendarIcons = [
    ['🗓', 'Відривний календар'], ['📅', 'Календар із датою'], ['▦', 'Сітка календаря'], ['▣', 'Контурна сітка'], ['▤', 'Рядки календаря'], ['⊞', 'Квадратна сітка'], ['◫', 'Подвійна рамка'], ['▧', 'Поділений календар'], ['◰', 'Кутова сітка'], ['⌑', 'Мінімалістичний'], ['▩', 'Контрастна сітка'], ['▥', 'Три секції'], ['▨', 'Компактний'], ['🗒', 'Аркуш дати'], ['◇', 'Нейтральний знак'],
  ].map(([symbol, name], index) => `<div class="calendar-icon-sample"><button type="button" class="calendar-symbol icon-style-${index + 1}" title="${name}">${symbol}</button><span>${index + 1}. ${name}</span></div>`).join('');
  const modals = ['Класичне підтвердження', 'Бічна панель', 'Нижній лист', 'Мінімалістичне', 'З іконкою', 'Крок за кроком', 'Попередження', 'З прогресом', 'Форма у два стовпці', 'Картка з підказкою', 'Темне', 'Контекстне', 'Розгорнуте', 'Діалог вибору', 'Повноекранне'].map((name, index) => `<div class="modal-sample modal-s${index + 1}"><header><strong>${index + 1}. ${name}</strong><span>×</span></header><p>${index % 3 === 0 ? 'Короткий текст із важливим поясненням дії.' : index % 3 === 1 ? 'Заголовок, опис і різні варіанти розташування кнопок.' : 'Приклад діалогу для роботи з даними.'}</p>${index % 4 === 1 ? '<input placeholder="Приклад поля">' : ''}<footer><button class="secondary">Скасувати</button><button class="primary">Підтвердити</button></footer></div>`).join('');
  return `<section class="design-test"><p class="note">Тестові варіанти. Дані тут не зберігаються.</p><h3>Поля введення</h3><div class="design-test-grid">${fields}</div><h3>Поля дати</h3><div class="design-test-grid">${dates}</div><h3>Піктограми календаря</h3><div class="calendar-icon-grid">${calendarIcons}</div><h3>Спливаючі вікна</h3><div class="modal-samples">${modals}</div></section>`;
}
